### ISSUE TITLE
FirebaseError: Firebase: No Firebase App '[DEFAULT]' has been created - call Firebase App.initializeApp() (app/no-app).

### ISSUE THREAD

**Issue by onuryilmazdev** [rturan29/refine-firebase#1]
firebase den normal bağlanıldığında data çekiliyor. ama refine a bağladığımda bu hatayı basıyor console a  çözümü nedir ?

**Comment by onuryilmazdev** [comment]
src altına firebase.js dosyasında

**Comment by rturan29** [comment]
peki bu dosyayı başka biryerden import ettiniz mi?

**Comment by onuryilmazdev** [comment]
app.tsx te import ettim buradaki import ayarları ile de import ettim sonra refineBasic projenizdeki ayarları da denedim..

import { firebaseAuth, firestoreDatabase } from './firebase';
const { auth, getAuthProvider, getPermissions } = firebaseAuth;
  const { getDataProvider } = firestoreDatabase;
  return (
    <Refine
      routerProvider={routerProvider}
      // dataProvider={dataProvider}
      dataProvider={getDataProvider()}
      // authProvider={getAuthProvider()}
      Title={Title}
      Header={Header}
      Sider={Sider}
      Footer={Footer}
      Layout={Layout}
      OffLayoutArea={OffLayoutArea}
      />

**Comment by onuryilmazdev** [comment]
https://github.com/onuryilmazdev/refine2 projeyi git e gönderdim firebase configlerini de açık gönderdim test projesi tamamen.

**Comment by holy-dev** [comment]
Is it solved?

**Comment by rturan29** [comment]
> Is it solved?

Not yet.

**Comment by holy-dev** [comment]
@rturan29 what is the issue?

**Comment by jjgumucio** [comment]
Same problem here...

**Comment by jjgumucio** [comment]
Well, reading the code I just realized that the function `initializeFirebase` is a reexport of `initializeApp` from Firebase.
So, I imported the original `initializeApp` from firebase and the _Default App_ error disappeared.
BUT, I got a new error: _Props is undefined_ for the props at FirebaseFirestore initialization...

**Comment by rturan29** [comment]
thanks, i will make correct these issue as soon as possible

**Comment by jjgumucio** [comment]
> thanks, i will make correct these issue as soon as possible

So @rturan29 do you need help to apply the changes?
Point me in the right direction and I can do it if you don't have the time

**Comment by rturan29** [comment]
Thanks for help. But `initializeFirebase` is already original firebase `initializeApp` function. I am only reexporting it. And I am passing this app object to constructers.
.
